apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: click-pvc
  namespace: click-app
spec:
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: click-app
  namespace: click-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: click-app
  template:
    metadata:
      labels:
        app: click-app
    spec:
      containers:
        - name: app
          image: docker.io/hius3010/click-app:1.0
          ports:
            - containerPort: 8888
          volumeMounts:
            - mountPath: /app/data
              name: click-storage
      volumes:
        - name: click-storage
          persistentVolumeClaim:
            claimName: click-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: click-app
  namespace: click-app
spec:
  type: NodePort
  selector:
    app: click-app
  ports:
    - port: 80
      targetPort: 8888
      nodePort: 30080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: click-app
  namespace: click-app
spec:
  host: click.ssc2.amigo
  to:
    kind: Service
    name: click-app
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

